### ISSUE TITLE
Section 2.16: Integer version of XrExtent2D should be unsigned

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/OpenXR-Docs#1]

**Comment by gigadude** [comment]
Negative extents are reasonable for e.g. flipping a rendered result.

**Comment by rpavlik** [comment]
Negative extents are explicitly prohibited by the spec. However, I believe this is left as signed to be similar to XrOffset (both members of XrRect).

If this proves confusing, we could add a XrExtend2Du for unsigned, perhaps?

**Comment by rpavlik** [comment]
This ship has sailed, sorry. We'll monitor if there is a lot of confusion around this, but I haven't heard any.
