### ISSUE TITLE
Are EXT functions missing the XR_ERROR_INSTANCE_LOST error return code?

### ISSUE THREAD

**Issue by pH5** [KhronosGroup/OpenXR-Docs#10]
Is there a system to whether or not a function can return the `XR_ERROR_INSTANCE_LOST` error code besides:
> 4.4.1. The Instance Lost Error
> Once XR_ERROR_INSTANCE_LOST is first returned, it must henceforth be returned by all functions that involve an XrInstance or child handle type until the instance is destroyed.

?

For example, `xrCreateInstance` can return `XR_ERROR_INSTANCE_LOST`, which I don't understand the purpose of. But the EXT functions are missing it. For example, neither `xrPerfSettingsSetPerformanceLevelEXT` nor `xrCreateDebugUtilsMessengerEXT` contain it in their list of failure return codes.

I would have expected all EXT functions that have an `XrInstance` or `XrSession` parameter to have the `XR_ERROR_INSTANCE_LOST` return value.

**Comment by brycehutchings** [comment]
Functions like `xrCreateDebugUtilsMessengerEXT` are implemented in the loader so there is no requirement on the state of the runtime's instance handle. However, extensions like `xrPerfSettingsSetPerformanceLevelEXT` do look like they should document `XR_ERROR_INSTANCE_LOST` as a possible error code.

**Comment by rpavlik** [comment]
I suspect that the fact the loader implements "create debug messenger" is an implementation detail and it should still specify it.  Note that the XR_ERROR_INSTANCE_LOST text quoted above did change somewhat in 1.0.0.

Makes me think the loader might itself have a bug because I imagine it's not tracking if instance lost was returned and then returning it itself for the debug functions.

**Comment by rpavlik** [comment]
So I thought this was fixed, but apparently wasn't. I have an internal MR now to fix it (and fix the scripts that were supposed to detect it), will be in the next release I assume.

**Comment by rpavlik** [comment]
Fixed in 1.0.16
