### ISSUE TITLE
Failed to load openxr runtime loader.(OPENXR, VALVE INDEX) 

### ISSUE THREAD

**Issue by Coskun7760** [KhronosGroup/OpenXR-Docs#100]
Hi,
I am trying to make a VR application using Open XR and Valve index header in Unity 2020.3.17.
In Unity 2019.xx, I was able to create VR applications by downloading Open VR and steam VR plugin from asset store.
But when I try to do it using Open XR in Unity 2020.3.17, I get an error and I searched for it on the internet, but I couldn't find a solution or I didn't understand it.

I can run the application with built and run it in the file menu. This way OpenXR, Valve index headers and controllers are working properly. But when I press the play button in the design and run it, I get the same error again.

The ERROR MESSAGE I got is as follows:
Failed to load openxr runtime loader.
UnityEngine.XR.Management.XRGeneralSettings:AttemptInitializeXRSDKOnLoad() (at Library/PackageCache/com.unity.xr.management@4.0.7/Runtime/XRGeneralSettings.cs:148)

**Comment by jackpr-unity** [comment]
This sounds like an issue with the project configuration. If you are still having this issue please submit a bug to Unity via the Bug Reporter, which is available in the "Help" menu of the editor.

<img width="196" alt="report a bug" src="https://user-images.githubusercontent.com/36174025/144907656-556a188c-1b87-458e-97fa-f151c12a88af.png">

**Comment by rpavlik** [comment]
Closing as being a project or Unity issue, rather than an issue with the specification.
