### ISSUE TITLE
XrInputSourceLocalizedNameGetInfo::sourcePath member description refers to "source"

### ISSUE THREAD

**Issue by amalon** [KhronosGroup/OpenXR-Docs#106]
The member descriptions section for XrInputSourceLocalizedNameGetInfo refers to a member "source", but the structure definition (and the openxr header I have to hand) call it sourcePath.

**Comment by rpavlik** [comment]
I mistook this for a related but more complex issue. I have since fixed it, it will be in the next patch release. Thanks!

**Comment by rpavlik** [comment]
Fix released in 1.0.26, thanks for your report!
