### ISSUE TITLE
[loader]doc: Use nativeLibraryDir to replace getNativeLibraryDir()

### ISSUE THREAD

**Issue by utzcoz** [KhronosGroup/OpenXR-Docs#108]
ApplicationInfo doesn't have method called getNativeLibraryDir(), and it only has nativeLibraryDir field, used by OpenXR loader source code. See https://developer.android.com/reference/android/content/pm/ApplicationInfo#nativeLibraryDir and https://gitlab.freedesktop.org/monado/utilities/openxr-android-broker/-/blob/main/utils/src/main/java/org/khronos/openxr/runtime_broker/utils/RuntimeData.java#L257-261.

Looks like the OpenXR-Docs repository doesn't host loader spec source code. There is a related PR for it at OpenXR-SDK-Source: https://github.com/KhronosGroup/OpenXR-SDK-Source/pull/278. As @rpavlik said at https://github.com/KhronosGroup/OpenXR-SDK-Source/pull/278#issuecomment-961363172, this issue is created at OpenXR-Doc for CLA reasons.

**Comment by rpavlik** [comment]
Oh.... I was pretty sure it was supposed to be in here. Ok, guess I'll merge the other one. 🤦

**Comment by utzcoz** [comment]
> Oh.... I was pretty sure it was supposed to be in here. Ok, guess I'll merge the other one. facepalm

I have saw build target for loader at spec Makefile from old PRs.

**Comment by rpavlik** [comment]
Merged over there, thanks!
