### ISSUE TITLE
FUNCTION_UNSUPPORTED error out of place on xrGetReferenceSpaceBoundsRect

### ISSUE THREAD

**Issue by Ralith** [KhronosGroup/OpenXR-Docs#11]
This seems to be the only core function that can declare itself unsupported. The only other functions that can return this error are `xrGetInstanceProcAddr` (for which it has a reasonable documented meaning) and extension functions.

**Comment by brycehutchings** [comment]
Good catch. This function was originally an extension and when it was moved into core, this error was not removed.

**Comment by rpavlik** [comment]
Hmm. Does make me wonder what the "not implemented yet" error code should be...

**Comment by rpavlik** [comment]
This (and all other error code issues, as far as I know) is fixed in 1.0.0.
