### ISSUE TITLE
Ambiguous description of XR_SPACE_LOCATION_ORIENTATION_VALID_BIT and XR_SPACE_LOCATION_ORIENTATION_TRACKED_BIT usage with respect to xrLocateSpace

### ISSUE THREAD

**Issue by rwilt001** [KhronosGroup/OpenXR-Docs#114]
In section [7.4.1](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#_xrlocatespace) of the OpenXR spec, usage of XR_SPACE_LOCATION_POSITION_VALID_BIT and XR_SPACE_LOCATION_POSITION_TRACKED_BIT is described for various scenarios such as:
> The runtime must return a location with both XR_SPACE_LOCATION_POSITION_VALID_BIT and XR_SPACE_LOCATION_POSITION_TRACKED_BIT set when locating space and baseSpace if both spaces were created relative to the same entity (e.g. two action spaces for the same action), even if the entity is currently untracked. The location in this case is the difference in the two spaces' application-specified transforms relative to that common entity.
>
however, usage of XR_SPACE_LOCATION_ORIENTATION_VALID_BIT and XR_SPACE_LOCATION_ORIENTATION_TRACKED_BIT is not discussed.

**Comment by rpavlik** [comment]
Fixed in 1.0.25! Thanks for the report!
