### ISSUE TITLE
XrSwapchainCreateInfo documentation broken links.

### ISSUE THREAD

**Issue by RocketTree** [KhronosGroup/OpenXR-Docs#115]
Hi, hope this is the correct place to report this tiny issue.

The links to XrSwapchainCreateFlags and XrSwapchainUsageFlags from the XrSwapchainCreateInfo member descriptions and valid usage documentation are both broken.

They both link to Create/UsageFlagBits (404 error) rather than Create/UsageFlags.

Cheers.

**Comment by rpavlik** [comment]
Thanks. I think I need to put some redirects in until I split the flags/flagbits ref pages, our current weird semi-merged thing is more headache than it's worth. I was thinking I had some kind of redirect or post-process but I guess not.

**Comment by rpavlik** [comment]
https://registry.khronos.org/OpenXR/specs/1.0/man/html/XrSwapchainCreateInfo.html for reference and easy checking. Unfortunately not fixed by the recent script upgrades.

**Comment by rpavlik** [comment]
This was fixed with the flag/flagbits cleanup in the most recent release. Thanks for the report!
