### ISSUE TITLE
XR_MIN_COMPOSITION_LAYERS_SUPPORTED not defined in spec

### ISSUE THREAD

**Issue by amalon** [KhronosGroup/OpenXR-Docs#117]
`XR_MIN_COMPOSITION_LAYERS_SUPPORTED` is mentioned twice in spec in relation to the minimum supported composition layers by a runtime, however it doesn't appear to be actually defined anywhere.

**Comment by rpavlik** [comment]
Looks like it's in the XML and the header, but we don't have an explicit documentation of it in the spec.

**Comment by rpavlik** [comment]
Fixed in 1.0.23. Thanks for the report!
