### ISSUE TITLE
XrHandTrackingAimStateFB should be provided to the next chain of 

### ISSUE THREAD

**Issue by kotowate** [KhronosGroup/OpenXR-Docs#124]
In specification/sources/chapters/extensions/fb/fb_hand_tracking_aim.adoc there is an information on how to use `XrHandTrackingAimStateFB` which is meant to store output for `xrLocateHandJointsEXT`. Right now it is said to be provided in the chain of `XrHandJointsLocateInfoEXT` which is input for the function. The output values are stored in locations param, `XrHandJointLocationsEXT`.

Right now, as it is implemented, providing `XrHandTrackingAimStateFB` in the `next` chain of `XrHandJointsLocateInfoEXT` does not fill the structure. Providing it in the `next` chain of `XrHandJointLocationsEXT` works.

Now it is:
`XrHandTrackingAimStateFB` can be provided in the `next` chain of `**XrHandJointsLocateInfoEXT**` when calling `xrLocateHandJointsEXT` to request aiming gesture information associated with this hand.

Should be changed to:
`XrHandTrackingAimStateFB` can be provided in the `next` chain of `**XrHandJointLocationsEXT**` when calling `xrLocateHandJointsEXT` to request aiming gesture information associated with this hand.

**Comment by rpavlik** [comment]
Thanks for your report! Someone else in the WG has also noticed this, so this is fixed in 1.0.23 (and was actually fixed internally when you filed this issue)
