### ISSUE TITLE
How to show oxr_error log?

### ISSUE THREAD

**Issue by coolcup74** [KhronosGroup/OpenXR-Docs#127]
I'd like to show oxr log on android log system.
Please let me know how to print out oxr logs.
Thank you.

**Comment by rpavlik** [comment]
Is this a question about Monado? If so, please seen https://monado.freedesktop.org to connect to our Discord chat or GitLab issues.

**Comment by rpavlik** [comment]
This is either a Monado question, or a loader question. I think the loader outputs all of its logs to logcat regardless of level though.
