### ISSUE TITLE
How to change view configuration to Mono from Stereo?

### ISSUE THREAD

**Issue by coolcup74** [KhronosGroup/OpenXR-Docs#128]
For testing purpose,
I'd like to change view configuration from Stereo to Mono.
Please let me know.

Thank you.

**Comment by Rectus** [comment]
The view configuration you want is passed to the `xrBeginSession()` call. Note that a mono view configuration does not make sense in a VR environment, and a VR runtime is unlikely to support it. What exactly are you trying to accomplish?

**Comment by rpavlik** [comment]
Yeah, the view configurations supported by a runtime are generally limited, I'm not sure there are any (conformant) runtimes yet that support a mono view configuration.

**Comment by rpavlik** [comment]
You would need a runtime that supports mono view configurations. You could submit the same view to left and right eyes if you wanted, I guess, but that's a separate thing.
