### ISSUE TITLE
unclear description of extension enum base

### ISSUE THREAD

**Issue by 3b** [KhronosGroup/OpenXR-Docs#148]
`appendix.adoc` says
> Note that all extension enums begin at the extension enum base of 1^10 (base 10). 

1^10 is 1, and the next most obvious interpretation I could think of (1e10) is off by a factor of 10.

Something like `... enum base of 10^9 (1,000,000,000).` would be more clear.

Might be nice to have the constants for generating extension enum values in `xr.xml` too, to avoid confusion, though I wouldn't be surprised if everyone just hard-coded them anyway.

**Comment by rpavlik** [comment]
Good catch! I didn't even realize it was in the spec, I thought it was only in the scripts. You're welcome to make the fix to the spec yourself, otherwise I'll leave this here flagged as an issue and I'll get to it eventually (or someone else in the WG will)

**Comment by rpavlik** [comment]
A change is in flight internally to fix this issue.

**Comment by rpavlik** [comment]
Fixed in 1.0.28, thanks for the report!
