### ISSUE TITLE
wrong heading level for 2.7.5 through 7?

### ISSUE THREAD

**Issue by 3b** [KhronosGroup/OpenXR-Docs#149]
[`2.7.5. Type Aliasing`](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#type-aliasing), [`2.7.6. Valid Usage`](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#valid-usage) and [`2.7.7. Implicit Valid Usage`](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#implicit-valid-usage) are included under [`2.7. API Layers`](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#api-layers) but don't seem to be specific to layers.

**Comment by rpavlik** [comment]
Good catch! Should be an easy fix, removing one character from those header lines.

**Comment by 3b** [comment]
Not as sure about these:

`10.4.1. Frame Rate`
`10.4.2. Compositing` 
`10.4.3. Composition Layer Flags`
`10.4.4. Composition Layer Blending`
`10.4.5. Composition Layer Types`  and 
`10.4.6. Environment Blend Mode`

are all under [`10.4. Frame Submission`](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#frame-submission) , but it seems more like `Frame Rate`, `Compositing` and `Environment Blend Modes` should be up one level at `10.x`, leaving the `Composition Layer ...` under `Compositing`.

**Comment by rpavlik** [comment]
Hmm. I wonder if something got messed up during an asciidoctor upgrade or something. I swear I've reviewed heading levels before. Thanks for noticing this, I'll look into it.

**Comment by rpavlik** [comment]
Fixed in 1.0.28, thanks for the report!
