### ISSUE TITLE
11.5.4. xrGetActionStatePose missing XR_ERROR_PATH_INVALID return value

### ISSUE THREAD

**Issue by pH5** [KhronosGroup/OpenXR-Docs#15]
In Section 11.5.4. Pose Actions, the function description for `xrGetActionStatePose` does not explain what the runtime does when the application passes an invalid `subactionPath` parameter, or a valid `subactionPath` that was not part of the `subactionPaths` the `action` was created with. It only states:

> See `XrActionCreateInfo` for a description of subaction paths, and the restrictions on their use.

There is no mention of `subactionPath` in the Valid Usage (Implicit) section. In the `XrActionCreateInfo` description it is stated that:

> If `subactionPaths` is specified and any of the following conditions are not satisfied, the runtime must return `XR_ERROR_PATH_INVALID`:
> * Each path provided is one of:
>   * /user/head
>   * /user/hand/left
>   * /user/hand/right
>   * /user/gamepad
>   * /user

This implies that only those five well-known paths are valid to be used as `subactionPath` parameter, but the Return Codes section for `xrGetActionStatePose`does not include the `XR_ERROR_PATH_INVALID` return value in case of a path that is not in this list, and it is not explained what will be returned if the path is in this list but was not given when creating the `action`.

**Comment by rpavlik** [comment]
Thanks for your report! This is resolved in 1.0.0: This is an instance of `XR_ERROR_PATH_UNSUPPORTED` (as in, the path may be a valid XrPath value that corresponds to something, it's just not a something that can be accepted there), which is explained in  https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrActionStateGetInfo
