### ISSUE TITLE
unclear wording in `Session Labels`

### ISSUE THREAD

**Issue by 3b** [KhronosGroup/OpenXR-Docs#150]
[12.26.4. Session Labels](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#session-labels) says

> All of a session’s label region’s must be closed by the [xrDestroySession](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#xrDestroySession) function is called for the given [XrSession](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XrSession).

Not sure if that is supposed to say ".. must be closed *before* the `xrDestroySession` function is called" or if it is trying to say `xrDestroySession` will close the regions. I assume the former since end region `must` be called for each begin region, but wouldn't be surprised by the latter either, if object handles are destroyed implicitly.

Also, it should probably be "regions" rather than "region's" unless there is something missing after it.

**Comment by rpavlik** [comment]
Good catch. I agree with your interpretation. I've made an internal MR to correct this accordingly, which will appear in an upcoming patch release if approved by the relevant stakeholders.

**Comment by rpavlik** [comment]
Fixed in 1.0.28, thanks for the report!
