### ISSUE TITLE
Incorrect/duplicate docs for `XrDebugUtilsMessengerCallbackDataEXT.sessionLabels`?

### ISSUE THREAD

**Issue by 3b** [KhronosGroup/OpenXR-Docs#151]
in [12.26.4. Session Labels](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#session-labels) in `XrDebugUtilsMessengerCallbackDataEXT` "Member Descriptions", `sessionLabels` is documented as 

> * sessionLabels is a pointer to an array of [XrDebugUtilsLabelEXT](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XrDebugUtilsLabelEXT) objects related to the detected issue. The array is roughly in order or importance, but the 0th element is always guaranteed to be the most important object for this message.
>
> * sessionLabels is NULL or a pointer to an array of [XrDebugUtilsLabelEXT](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XrDebugUtilsLabelEXT) active in the current [XrSession](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XrSession) at the time the callback was triggered. Refer to [Session Labels](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#session-labels) for more information.

First description looks like something that was accidentally left in after editing it into the second, since it refers to `objects` instead of `labels` and has wrong order. (order is later described as "The labels listed inside `sessionLabels` are organized in time order, with the most recently generated label appearing first, and the oldest label appearing last.").

Also, the `objects` description (and the incorrect `sessionLabels`) says "... roughly in order or importance" which should probably be "... roughly in order *of* importance"? Possibly also should mention the possibility of being `NULL`, since `objectCount` can be `0`.

**Comment by rpavlik** [comment]
Good catch. I agree with your interpretation. I've made an internal MR to correct this accordingly, which will appear in an upcoming patch release if approved by the relevant stakeholders.

**Comment by rpavlik** [comment]
Fixed in 1.0.28, thanks for the report!
