### ISSUE TITLE
Formatting mistake in XR_OPPO_controller_interaction

### ISSUE THREAD

**Issue by amini-allight** [KhronosGroup/OpenXR-Docs#156]
The list of left hand only inputs for `XR_OPPO_controller_interaction` doesn't have its formatting applied correctly, making it difficult to read. See the attached image.

![image (1)](https://github.com/KhronosGroup/OpenXR-Docs/assets/81187258/92c0d6dc-cf86-4ec0-ab67-25f32000047f)

**Comment by rpavlik** [comment]
Good catch, sorry we missed that! I must not have re-looked at the HTML after a final revision of the input adoc.

**Comment by rpavlik** [comment]
OK, I have a fix internally for this, I anticipate it will be in the next patch release.

**Comment by rpavlik** [comment]
Fixed in 1.0.29!
