### ISSUE TITLE
12.15. xrGetVisibilityMaskKHR missing XR_ERROR_SESSION_LOST return value

### ISSUE THREAD

**Issue by pH5** [KhronosGroup/OpenXR-Docs#16]
The `xrGetVisibilityMaskKHR` function is passed a `session` parameter, but its Return Codes section does not inlcude the `XR_ERROR_SESSION_LOST` return value.

**Comment by rpavlik** [comment]
Thanks for your report! This is resolved in 1.0.0, and shouldn't be able to return now that we have https://github.com/KhronosGroup/OpenXR-Docs/blob/master/specification/scripts/xml_consistency.py
