### ISSUE TITLE
macOS and Metal support

### ISSUE THREAD

**Issue by chnoblouch** [KhronosGroup/OpenXR-Docs#161]
The spec doesn't seem to have an extension for Apple's Metal API (```XR_KHR_metal_enable```?), so it looks like applications on macOS have to render using the deprecated OpenGL API or hope that the runtimes implement ```XR_KHR_vulkan_enable2``` using MoltenVK. I also couldn't find a section in the loader documentation that specifies how runtimes are discovered on macOS, but maybe this works the same way as on Linux.

Is macOS simply not really supported at the moment or am I missing something?

(I posted this question on the OpenXR forum a few weeks ago, but haven't gotten a reply yet, so I'm opening an issue here now. [Here's the link](https://community.khronos.org/t/support-for-metal-graphics-bindings/110302).)

**Comment by rpavlik** [comment]
I responded to your forum post just now, thanks for your patience. Basically a matter of vendor support, the loader should build on Mac but I can't test it. I think others do, though.

**Comment by chnoblouch** [comment]
Looking at the [OpenXR 1.1 launch presentation](https://www.khronos.org/assets/uploads/developers/presentations/Khronos_OpenXR_1.1_Embargo_15April24_.pdf), it seems like Metal support is in the pipeline. Thank you for the great work you're doing to enable cross-platform XR applications.
