### ISSUE TITLE
Semantics of relative inputs are unclear

### ISSUE THREAD

**Issue by Ralith** [KhronosGroup/OpenXR-Docs#17]
§6.3.2 defines:
> trackball - A 2D relative input source. These sometimes include click components.

However, no other mention is made of relative input. This leaves the exact behavior of actions bound to the input ambiguous: if `xrGetActionStateVector2f` returns an instantaneous sample of the relative input, significant error accumulation is likely due to missed inputs. A runtime could continuously integrate inputs between calls to `xrSyncActionData` to prevent error accumulation, but this is not required (or perhaps even permitted?) by the spec, and is inconsistent with the presumed instantaneous sampling of other inputs. Completely lossless processing of relative inputs ultimately requires an input event queue, which OpenXR does not currently provide.

Possibly also relevant is the reservation of `/user/treadmill`, which implies a relative input source.

A similar problem exists for instantaneous inputs, as for example might be emitted by a device or runtime that implements gesture recognition or threshold events.

CC @rpavlik

**Comment by rpavlik** [comment]
This will need to be addressed before any trackball-containing interaction profiles are added to the spec. None exist now (as is the case for most of those, we wanted to establish spelling/names in advance for extension, etc. usage).

**Comment by Ralith** [comment]
Having thought on this a bit more, I'm coming around more in favor of runtime-side integration rather than an event queue, as it moots the question of polling rate.

**Comment by rpavlik** [comment]
Yeah, I think there may not be any relative devices for a while. We'll definitely address that if one comes up that makes sense to expose as an event-style relative input rather than runtime-integrated.
