### ISSUE TITLE
Internal links broken in 1.1.36 PDF

### ISSUE THREAD

**Issue by amalon** [KhronosGroup/OpenXR-Docs#170]
In xrspec.pdf 1.1.36, none of the internal links (e.g. contents page, links to functions like xrWaitFrame) seem to work. 
https://registry.khronos.org/OpenXR/specs/1.1/pdf/xrspec.pdf

In 1.0.34 they work fine.
https://registry.khronos.org/OpenXR/specs/1.0/pdf/xrspec.pdf

**Comment by rpavlik** [comment]
oh, yikes! Not sure how that happened. The table of contents in the PDF itself (usually shows in the sidebar) works but I had not tested the links recently.

**Comment by rpavlik** [comment]
OK, so when I build just a simple no-extensions PDF locally I have links working properly.

**Comment by rpavlik** [comment]
OK, I think an update to the PDF optimizer used is at fault, I've got a fix in place for the next release.

**Comment by rpavlik** [comment]
Yes, those PDFs will be replaced once the next patch release comes out very soon
