### ISSUE TITLE
Unclear parent of XrSpace created by xrCreateActionSpace

### ISSUE THREAD

**Issue by jzulauf-lunarg** [KhronosGroup/OpenXR-Docs#178]
The xr.xml defines the parent of XrSpace as the XrSession, but the text states that the XrAction is the parent of the `XrSpace` created by `xrCreateActionSpace` for purposes of implicit destruction.

From the registry `XrSpace` is defined:

`<type category="handle" parent="XrSession"><type>XR_DEFINE_HANDLE</type>(<name>XrSpace</name>)</type>`

thus be subject to the  general

> Handles form a hierarchy in which child handles fall under the validity and lifetime of parent handles. 

which would imply all `XrSpace` objects would be destroyed when the parent `XrSession` is destroy.

In contrast, this body text for `xrCreateActionSpace` states :

> The [XrSpace](https://registry.khronos.org/OpenXR/specs/1.1/html/xrspec.html#XrSpace) handle must be eventually freed via the [xrDestroySpace](https://registry.khronos.org/OpenXR/specs/1.1/html/xrspec.html#xrDestroySpace) function or by destroying the parent [XrAction](https://registry.khronos.org/OpenXR/specs/1.1/html/xrspec.html#XrAction) handle.

Does this imply that `XrSpace` created by `xrCreateActionSpace`  remains undestroyed after `xrDestroySession` is called, and not destroyed as all other `XrSpace` handles created with `xrCreate.*(XrSession session, ...)`?  Or is it saying the destruction of *either* the `XrAction` or the `XrSession` will cause the implicit destruction of created `XrSpace`?

**Comment by rpavlik** [comment]
That is an error in the spec, the parent is XrSession for all XrSpace handles. There is text somewhere that says how an action space behaves after destroying the action, iirc.

**Comment by rpavlik** [comment]
Fixed in the latest release. Thanks for the report!
