### ISSUE TITLE
Section 2.13.1 XrDuration should be an unsigned value

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/OpenXR-Docs#2]
Specification should specify that 

> The _absolute value of the_ difference between two timepoints is a duration, ...

**Comment by pH5** [comment]
I think it is signed on purpose. For example:
> XR_MIN_HAPTIC_DURATION is used to indicate to the runtime that a short haptic pulse of the minimal supported duration for the haptic device.
> `#define XR_MIN_HAPTIC_DURATION -1`

**Comment by jherico** [comment]
`XR_MIN_HAPTIC_DURATION` looks like a sentinel value.  It would then only ever used to compare for equality, not LT/GT.  So it would be perfectly reasonable to use a max-unsigned value like `#define XR_MIN_HAPTIC_DURATION (~0ULL)` or `#define VK_ATTACHMENT_UNUSED (~0U)` depending on the underlying type.

**Comment by yl-msft** [comment]
std::chronos::duration is using signed integers for integer version of duration:

https://en.cppreference.com/w/cpp/chrono/duration


std::chrono::nanoseconds | duration</*signed integer type of at least 64 bits*/, std::nano>
-- | --

**Comment by jherico** [comment]
OK, I guess that makes sense.  A duration being the difference between two timepoints, the sign can tell you which of the timepoints was before the other one.
