### ISSUE TITLE
XrPath is excessively UB-prone

### ISSUE THREAD

**Issue by Ralith** [KhronosGroup/OpenXR-Docs#20]
The spec states:
> An XrPath that is received from one XrInstance may not be used with another. Such an invalid use may be detected and result in an error being returned, or it may result in undefined behavior.

and

> These XrPath values are only valid within a single XrInstance, and must not be shared between instances. Applications must instead use the string representation of a path in their code and configuration, and obtain the correct corresponding XrPath at runtime in each XrInstance

As the author [openxrs](https://github.com/Ralith/openxrs), I'm trying to develop memory-safe Rust bindings for OpenXR. This means that every API call that isn't explicitly an unsafe escape hatch must not be capable of invoking undefined behavior. The above restrictions make this very difficult, as either anything that operates on an `XrPath` is potentially unsafe, representing a significant portion of the API. This makes it much harder to audit downstream code for safety violations. My only alternative is to represent `XrPath`s with a wrapper that tracks the associated instance, but that would undermine their value as compact lightweight tokens that can be trivially copied and stored.

Most implementations will likely implement `XrPath` as indexes into an internal table that can be bounds-checked, and path type-checking is already required, so guaranteeing defined behavior here seems reasonable.

CC @rpavlik

**Comment by Ralith** [comment]
Note that this is not an issue for object handles, because it's much more natural for those to be exposed as larger, non-copyable types.

**Comment by rpavlik** [comment]
Thanks for filing this! A corresponding issue (number 1149) has been raised within the working group.

I'm personally interested in resolving this apparent weakness, since XrPath atoms are intended to be more lightweight and usable than the path strings they represent, so I would consider it a design flaw if they aren't usable like this in practice.

**Comment by rpavlik** [comment]
We intended to solve this with 1.0.0. If there are still places where the language is unclear, please let us know here. (Leaving issue open per chat)

**Comment by rpavlik** [comment]
closed in favor of #22
