### ISSUE TITLE
Questions about Session lifecyle state

### ISSUE THREAD

**Issue by sinojelly** [KhronosGroup/OpenXR-Docs#21]
In the [state transition diagram](https://www.khronos.org/registry/OpenXR/specs/0.90/html/xrspec.html#session-lifecycle-states
) , when the application calls xrEndSession, Runtime will switch from the Stopping state to the Idle state, and then switch to the Exiting state when the user issues an exit request.
I don't quite understand how user quite request affects state switching. Which openxr function is called by the application?
My understanding is that when the application calls xrEndSession, Runtime switches from Stopping to Exiting? is it right?Thanks!

**Comment by brycehutchings** [comment]
> My understanding is that when the application calls xrEndSession, Runtime switches from Stopping to Exiting? is it right?Thanks!

Not quite. The state will transition from Stopping to Idle and then its up to the runtime to decide when to transition to either Ready or Exiting. In OpenXR 0.90, the decision of how to transition states is up to the runtime. For example, a runtime may support task switching and keep an app in Idle while another app is in focus, and then move the original app from Idle to Ready when the user switches back. That same runtime may support a sort of XR task manager and terminate background XR apps, in which case the runtime would transition the apps from Idle to Exiting. In OpenXR 0.90, there is no mechanism for the app to instruct the runtime that it wants to transition to Exiting.

In OpenXR 1.0 we are adding a method for an app to ask to be transitioned to the Exiting state. This will enable the scenario where the app itself wants to control gracefully ending its Session.

**Comment by rpavlik** [comment]
@brycehutchings can you re-review and determine if this is resolved in 1.0?

**Comment by brycehutchings** [comment]
We've cleaned up this and it is now good. xrRequestExitSession is there to instruct the runtime the application wishes to transition to EXITING state. We've also improved the description of the session states and how they transition, including the independent "running" state that exists between xrBeginSession and xrEndSession.
