### ISSUE TITLE
Begin/EndFrame session parameter missing from list of externally synchronized parameters

### ISSUE THREAD

**Issue by Ralith** [KhronosGroup/OpenXR-Docs#23]
10.4 states:

> While xrBeginFrame and xrEndFrame do not need to be called on the same thread, the application must handle synchronization if they are called on separate threads.

However, there is no "Thread Safety" block associated with either function, and section 2.3 does not mention them. The required behavior is clear, but should probably be cross-referenced for ease of discoverability like the other cases.

**Comment by rpavlik** [comment]
This is being tracked internally at https://gitlab.khronos.org/openxr/openxr/issues/1216

**Comment by rpavlik** [comment]
We have improved our description of this, but apparently I never put it in the XML yet.

**Comment by rpavlik** [comment]
OK, I have an internal MR for this up.

**Comment by rpavlik** [comment]
Fixed in 1.0.23. Thanks for the report!
