### ISSUE TITLE
Please provide a GPL compatible license for headers

### ISSUE THREAD

**Issue by jbkempf** [KhronosGroup/OpenXR-Docs#3]
The provided headers are under Apache 2 and are therefore not usable from any LGPLv2.1 or GPLv2 project.

**Comment by rpavlik** [comment]
Does the Apache 2 + exception as used in Vulkan work for your needs?

**Comment by jbkempf** [comment]
Vulkan seems Apache2 only here:
https://github.com/KhronosGroup/Vulkan-Headers/blob/master/LICENSE.txt
https://github.com/KhronosGroup/Vulkan-Loader/blob/master/LICENSE.txt

So, maybe, but as far as I can see, all Khronos is moving to Apache2, which makes all the recent projects unusable...

**Comment by rpavlik** [comment]
I mean the exception that's in the vulkan XML file - is this license notice OK?

https://github.com/KhronosGroup/Vulkan-Headers/blob/master/registry/vk.xml

I would propose applying it not just to the XML in the OpenXR case, but also to the static and generated headers.

**Comment by jbkempf** [comment]
Yes, that would work totally.

>  I'd personally like to see the exception applied to all apache-2 licensed registry XML and API headers in Khronos standards, and for that to be the default going forward, but I need a bit of help making that case

The fact that this is not the default for all Khronos work is mind-blowing. Moving from MIT to Apache2 is a huge restriction... I don't get it.

**Comment by rpavlik** [comment]
I don't get it either, but I'm not a lawyer. Presumably the lawyers of the many Khronos decided for some reason it better served the interests of the group. Personally I would support the same default :) but that's just me speaking for myself.

Thanks for the feedback - am proposing exactly that. Hopefully it will get approved and I can push an update with it, though it will require some legal review so unfortunately it may take a while.

**Comment by oddhack** [comment]
We might eventually modify all the Apache 2-licensed files to incorporate the exception clause. Like all licensing decisions, it's a very slow process as something of that scope requires buy-in across all the working groups and companies in Khronos. In the meantime we're doing it on demand, and the only demand for Vulkan was on vk.xml.

**Comment by rpavlik** [comment]
I wanted to pop in and update that this is not forgotten and is still in progress, it just unfortunately didn't make it for 1.0.0.

**Comment by jbkempf** [comment]
Any update on this?

**Comment by rpavlik** [comment]
I'll poke the right people to check what the status is - I've been wondering myself.

**Comment by oddhack** [comment]
I followed up at our recent F2F meeting and there is a planned vote at the October Board of Promoters meeting to let us move forward with using the Apache 2 + (L)GPL exception clause license broadly within Khronos. Hopefully this will be resolved within a month or so.

**Comment by GeekyGami** [comment]
Any word on this at the moment?

**Comment by jbkempf** [comment]
Not heard anything.

**Comment by rpavlik** [comment]
Still in progress, we haven't forgotten. Sorry there's nothing we can share right now.

**Comment by rpavlik** [comment]
Would this work?

> SPDX-License-Identifier: Apache-2.0 OR MIT

(that is, dual licensed, apache-2.0 or MIT aka expat, your choice. contributions under both of course)

**Comment by jbkempf** [comment]
Yes, MIT is valid.

**Comment by rpavlik** [comment]
Resolved in 1.0.10! The header files in `openxr/`, as well as the XML, have been relicensed - see changelog or the files themselves for more. Thanks for your patience, everyone!

**Comment by jbkempf** [comment]
Thanks.
