### ISSUE TITLE
xrGetVulkanInstanceExtensionsKHR should better specify the output format

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/OpenXR-Docs#31]
Specifically xrGetVulkanInstanceExtensionsKHR should specify whether the output buffer will be null terminated when it returns.

**Comment by rpavlik** [comment]
Hmm. Doesn't it say somewhere in the spec (fundamentals?) that all strings are null-terminated?

**Comment by rpavlik** [comment]
That seems reasonable to me, I'll bring it to the group. I'm pretty sure we already say utf-8 in places. FWIW, the anchor is `string-encoding` for the link.

**Comment by rpavlik** [comment]
Upon review, the parameter right above (size) is described as "including the null terminator", and all strings are specified in fundamentals to be null-terminated. (I imagine it's the fact that you're receiving a length is the source of confusion, but it does not change the overall requirement of returning null-terminated strings.) The WG has chosen to close this issue without making a specification change.  Hope this helps!
