### ISSUE TITLE
Reference guide PDF incorrectly marks the `component` portion of a subpath as required

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/OpenXR-Docs#32]
The current [reference guide](https://www.khronos.org/files/openxr-10-reference-guide.pdf) contains this

![image](https://user-images.githubusercontent.com/1533642/64970877-8797b200-d85b-11e9-88b8-15499d7c0fd4.png)

However, section [6.3.2](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#semantic-path-reserved) specifically marks the component portion of the path as optional: `…/input/<identifier>[_<location>][/<component>]`

This can be confusing if you're going by the reference guide, since it's not apparent that `.../input/thumbstick` should be used for a Vector2f instead of `.../input/thumbstick/value`

**Comment by rpavlik** [comment]
Fixed in revision 0421 of the reference guide, which I just uploaded. Thanks for the report!
