### ISSUE TITLE
Meaning of "invalid" position/orientation unclear

### ISSUE THREAD

**Issue by Ralith** [KhronosGroup/OpenXR-Docs#35]
When components of an `XrPosef` are deemed invalid due to `XrViewStateFlags` or `XrSpaceLocationFlags`, it's unclear what guarantees are made about the components in question. Possibilities include:
- They aren't written at all, and hence contain whatever they did before the call was made, including possibly remaining uninitialized.
- Undefined data, possibly including a trap representation, is written, so reading from them is UB.
- Garbage data is written, so initialization is guaranteed and reading is defined, but there may be NaNs or a quaternion may be of non-unit length
- Well-formed data is written, i.e. all floats are finite and the quaternion is of unit length, but no guarantees are made about the usefulness of this data.

Given the possibility of undefined behavior, the exact outcome should be made explicit.

**Comment by Ralith** [comment]
> Is there some verbiage you could suggest that would effectively prohibit "malicious" runtime design

I think a well-meaning runtime could reasonably end up with such behavior, for example if it populates the struct by copying out of some internal state which might never have been initialized in "invalid" cases, e.g. if the pose hasn't been successfully tracked since the system started.

A permissive UB-free approach could look like like:

When a field of an output `XrPosef` value is associated with an unset `XR_SPACE_LOCATION_POSITION_VALID_BIT` or `XR_SPACE_LOCATION_ORIENTATION_VALID_BIT` or analogous unset bits in `XrViewStateFlags`, that field is deemed "invalid." Invalid fields **must** be populated by the implementation with data that does not include invalid representations for the individual scalars the field is composed of, i.e. trap representations are forbidden. The fields may otherwise contain arbitrary data.

This could be further weakened by allowing implementations to not write at all, which would be slightly more hazardous.

> Information on your use case might be helpful as well to explain to the WG.

It may sometimes be convenient to structure code to read from the possibly-invalid `XrPose` fields before checking the associated flags, for example to convert it to a math library's preferred representation. If doing so is UB, that should be made clear so that users, myself included, can take care not to.

**Comment by rpavlik** [comment]
We clarified this at some point, that you are not supposed to read any field for which the validity flag is not set. See https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSpaceLocationFlagBits - 

> - XR_SPACE_LOCATION_ORIENTATION_VALID_BIT - ... Applications **must** not read the pose field’s orientation if this flag is unset
> - XR_SPACE_LOCATION_POSITION_VALID_BIT - ... Applications **must** not read the pose field’s position if this flag is unset.
"


If you prefer everything zero-initialized or similar, you can copy the fields that are flagged as valid into an initialized structure before proceeding - that was the suggestion I heard from the group.

**Comment by Ralith** [comment]
Thanks, that's very clear!

**Comment by Ralith** [comment]
Should similar notes be added to the `XR_SPACE_VELOCITY_*_VALID_BIT`?

**Comment by rpavlik** [comment]
Yeah I just noticed that shortly after closing this. It will miss this next release but will hit the next one if I do it Monday.

**Comment by Ralith** [comment]
Also missing from `XR_VIEW_STATE_ORIENTATION_VALID_BIT`, but *not* `XR_VIEW_STATE_POSITION_VALID_BIT`.

**Comment by rpavlik** [comment]
Good catch, I'm including a fix for that too.

**Comment by rpavlik** [comment]
Fixed in 1.0.23. Thanks for the report!
