### ISSUE TITLE
Buffer Size Parameter elementCountOutput inconsistency

### ISSUE THREAD

**Issue by pH5** [KhronosGroup/OpenXR-Docs#4]
The Buffer Size Parameter Behavior section states:
> 2.11. Buffer Size Parameters

> Buffer Size Parameter Behavior
> * Independent of `elementCapacityInput` or `elements` parameters, `elementCountOutput` **must** be a valid pointer, and the function sets `elementCountOutput`

But the Valid Usage (Implicit) sections of many functions seem to imply that their `elementCountOutput` parameter may be `NULL`. For example:
> 7.3.1. xrEnumerateReferenceSpaces

> Valid Usage (Implicit)
> * If `spaceCountOutput` is not `NULL`, `spaceCountOutput` **must** be a pointer to a `uint32_t` value

Why not just:
 * `spaceCountOutput` **must** be a pointer to a `uint32_t` value

**Comment by brycehutchings** [comment]
Agreed we should simplify it to just be required, especially because there is no guarantee in the spec that the elementCountOutput won't change between calls (it's explicitly called out that the elementCountOutput can change). It seems like the two-call idiom section contradicts itself both saying elementCountOutput must be a valid pointer and that it can be null for some cases:

>* Independent of elementCapacityInput or elements parameters, **elementCountOutput must be a valid pointer, and the function sets elementCountOutput**.
> * [...]
> * **elementCountOutput can be NULL for cases** in which elementCapacityInput is greater than 0, in which case it is unused by the function. However, XR_ERROR_SIZE_INSUFFICIENT may still be returned by the function in the case that elementCapacityInput is too small.

**Comment by rpavlik** [comment]
This has been clarified in 1.0.0 to always be required. Additionally, in most cases, the value can only change at distinct points in time, so it should generally be constant, but we've made it always required anyway.
