### ISSUE TITLE
Grip spaces should have diagrams

### ISSUE THREAD

**Issue by Manishearth** [KhronosGroup/OpenXR-Docs#44]
https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#_standard_identifiers

![image](https://user-images.githubusercontent.com/1617736/77968441-32be0500-729c-11ea-9a3f-d70ec24d1044.png)

The +Y axis is defined as "the Y axis implied by the given right handed X and Z axes". This would be fine, except:

 - It's a bit tricky to use the right handed thumb rule on your own hands
 - The Z axis is defined as -Z
 - We have X and Z defined, and need to find Y
 - The X axis points in a different direction for each hand

All these put together is a recipe for sign error. At the very least we should say that it "roughly points inwards towards the arm", but a diagram would be ideal.

**Comment by rpavlik** [comment]
Thanks for filing this. The working group is looking to how we can clarify this text and add diagrams.

**Comment by rpavlik** [comment]
Thanks for bringing this up. The working group has reviewed the language (I think 1.0.17 had a rephrase) and added a diagram in 1.0.18.
