### ISSUE TITLE
Clarify restrictions imposed on Vulkan application access to swapchain images

### ISSUE THREAD

**Issue by Ralith** [KhronosGroup/OpenXR-Docs#50]
The spec says:
> Once an application is done writing to a swapchain image, it is released.

"done writing" is ambiguous. For Vulkan, the ideal arrangement is that the application releases an image after submitting work, which will write to the swapchain image, to the queue identified by the `XrGraphicsBindingVulkanKHR` it supplied. However, the actual physical write will probably not have occurred at that point, so a strict reading of the spec might require that the application block the CPU until the work is complete, which would be a disaster for performance.

Similarly, the `VK_KHR_vulkan_enable` text refers to the state of the swapchain image in present tense, e.g.

> When an application releases a swapchain image [it must have] a memory layout compatible with `VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL`

whereas in practice this is not true until after submitted work, which should not block the CPU, has been executed.

A reasonable implementation will manage synchronization by inserting image memory barriers and semaphore signal/await operations inside the OpenXR API calls permitted to access the Vulkan queue in question. The spec should explicitly guarantee that applications are not required to block the CPU on their graphics work or perform any additional synchronization beyond that already explicitly required by `VK_KHR_vulkan_enable`.

**Comment by rpavlik** [comment]
This was fixed in 1.0.13 - there was an error in the changelog fragment leading me to not realize it until now.
