### ISSUE TITLE
What is the difference between parentstruct and structextends?

### ISSUE THREAD

**Issue by expipiplus1** [KhronosGroup/OpenXR-Docs#51]
These seem to be used in similar number in the specification. Confusingly the line `parentStructs = type_elem.get('structextends')` appears in `reg.py`. 

I had a cursory search in the repository but it wasn't immediately clear what the semantic difference is.

**Comment by expipiplus1** [comment]
Ah, I see that parent struct doesn't mean an extended struct, but is used to implement some form of polymorphism over the children structs, i.e. one passes an `XrEventDataInstanceLossPending*` directly where an `XrEventDataBaseHeader` is expected.

Perhaps this distinction could be spelled out in the documentation or schema somewhere?

**Comment by rpavlik** [comment]
Good catch - this is something that is a little confusing, and that phrasing you found in the code is annoying.

I've added some comments to the relax-ng compact schema, and I'll fix those variable names too. For most purposes, you can use the Vulkan schema docs for OpenXR - OpenXR's schema is nearly a strict subset.

**Comment by expipiplus1** [comment]
Thanks!

> For most purposes, you can use the Vulkan schema docs for OpenXR - OpenXR's schema is nearly a strict subset.

Good to know. Is this a happy coincidence or does Khronos work to make sure that these stay compatible?

**Comment by rpavlik** [comment]
It's an artifact of heritage (OpenXR basically started with a fork of the Vulkan tooling) but also somewhat intentional - we try not to diverge so the toolsets can be similar. Ideally, we'd like to have most of our spec tooling extracted into e.g. a pypi package with just the specification-specific "business logic" code in each individual WG's repo.

**Comment by rpavlik** [comment]
Fixes released with 1.0.11

**Comment by expipiplus1** [comment]
Thanks!
