### ISSUE TITLE
New error code for xrCreateSession if XrGraphicsRequirements has not been called

### ISSUE THREAD

**Issue by liaxim** [KhronosGroup/OpenXR-Docs#53]
In case xrCreateSession is called before any of the XrGraphicsRequirements APIs, a specific error code can help identify the problem. XR_ERROR_VALIDATION_FAILURE is not clear enough. Please consider including a new error code in a maintenance extension.

**Comment by rpavlik** [comment]
Fixes released with 1.0.11
