### ISSUE TITLE
Swapchain images cannot be used as Vulkan input attachments

### ISSUE THREAD

**Issue by Ralith** [KhronosGroup/OpenXR-Docs#56]
`XrSwapchainUsageFlags` has no value that is guaranteed to map to `VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT`. This makes it impossible to perform certain kinds of efficient post-processing directly on swapchain images.

For color attachments this may not be a serious problem since many applications will render to a non-swapchain image for e.g. HDR, but for depth attachments that an application requires input attachment use for, the application must either perform a redundant copy or use less-efficient sampled image access.

**Comment by rpavlik** [comment]
1.0.10 includes a vendor extension addressing this for now. The WG is still working on a more complete solution.

**Comment by rpavlik** [comment]
Oops, how did I miss this? The vendor extension has been promoted to KHR as of 1.0.18. Thanks for the report!
