### ISSUE TITLE
Build instructions omit requirement for python3-jinja2

### ISSUE THREAD

**Issue by mrwonko** [KhronosGroup/OpenXR-Docs#61]
I'm trying to generate the headers via `make header` on WSL, so I followed the "Debian-derived Linux (including Ubuntu and Ubuntu on WSL)" instructions from the readme. But upon running `make header` in the specification folder, I got the following error:

```
[genxr]       registry/xr.xml -> out/1.0/openxr/openxr.h
[genxr]       registry/xr.xml -> out/1.0/openxr/openxr_platform.h
[genxr]       registry/xr.xml -> out/1.0/openxr/openxr_reflection.h
Traceback (most recent call last):
  File "./scripts/genxr.py", line 473, in <module>
    genTarget(args)
  File "./scripts/genxr.py", line 363, in genTarget
    diagFile=diag)
  File "<local path>/OpenXR-Docs/specification/scripts/creflectiongenerator.py", line 56, in __init__
    self.env = make_jinja_environment(file_with_templates_as_sibs=__file__)
  File "<local path>/OpenXR-Docs/specification/scripts/jinja_helpers.py", line 99, in make_jinja_environment
    from jinja2 import Environment, FileSystemLoader
ModuleNotFoundError: No module named 'jinja2'
make: *** [Makefile:189: out/1.0/openxr/openxr_reflection.h] Error 1
```

I could fix it by running `sudo apt install python3-jinja2`. That package should probably be added to the instructions in the readme.

**Comment by rpavlik** [comment]
Interesting - so this is actually bundled in most of the repos. Guess I must have accidentally excluded it here. Thanks for the report, I'll fix this for the next release.

**Comment by rpavlik** [comment]
This was fixed by bundling it, as I meant to the entire time.
