### ISSUE TITLE
Vulkan graphics requirements API version semantics are ambiguous

### ISSUE THREAD

**Issue by Ralith** [KhronosGroup/OpenXR-Docs#62]
[`XrGraphicsRequirementsVulkanKHR`](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrGraphicsRequirementsVulkanKHR)'s `minApiVersionSupported` is specified as:

> the minimum version of Vulkan that the runtime supports.

However, Vulkan has two different notions of version: the instance version, and the physical device version. It doesn't seem to be specified which of these should be checked against. The device version is usually the most important, but since the XR runtime is responsible for selecting the device it might be expected to perform that check itself.

An application can probably be safe by checking both versions, but explicitly documenting the desired behavior would reduce the odds of people making an incorrect assumption as to which matters, as I've inadvertently done in the past.

**Comment by rpavlik** [comment]
Addressed in 1.0.13 release.  (Answer: Instance version because runtime selects the device.)
