### ISSUE TITLE
Is it possible to clarify what type of images are allowed to be passed to xrEnumerateSwapchainImages

### ISSUE THREAD

**Issue by expipiplus1** [KhronosGroup/OpenXR-Docs#68]
https://www.khronos.org/registry/OpenXR/specs/1.0/man/html/xrEnumerateSwapchainImages.html

It would be good if this documentation would clarify what happens if I pass `XrSwapchainImageOpenGLKHR` when the swapchain is from a Vulkan device for example.

I would expect that either:

- The structures are untouched and an error code is returned
- Undefined behavior 

happens.

**Comment by rpavlik** [comment]
Straw poll indicates that a validation failure will be returned. I don't remember offhand if we make any guarantees about output data modification on an error, I think you have to treat it as possibly all invalid. We'll make an update to the spec to clarify this behavior, thanks for the report!

**Comment by rpavlik** [comment]
Resolved in 1.0.15

**Comment by expipiplus1** [comment]
Thanks for the resolution!
