### ISSUE TITLE
12.13 Wayland section of KHR_opengl_enable refers to incorrect struct

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/OpenXR-Docs#7]
https://github.com/KhronosGroup/OpenXR-Docs/blame/master/specification/sources/chapters/extensions/khr/khr_opengl_enable.adoc#L171

refers to `XrGraphicsBindingOpenGLWin32KHR` instead of `XrGraphicsBindingOpenGLWaylandKHR`

**Comment by rpavlik** [comment]
Fixed in 1.0.0.
