### ISSUE TITLE
input/output structure usage is not consistently specified

### ISSUE THREAD

**Issue by expipiplus1** [KhronosGroup/OpenXR-Docs#70]
The documentation for `xrGetVisibilityMaskKHR` says:

> visibilityMask is an input/output struct which specifies the view mask.

However the documentation for `xrGetControllerModelPropertiesMSFT` says:

> properties is a XrControllerModelPropertiesMSFT returns the properties of the controller model

It would be nice if the language of the former could be used for every input/output struct.

Additionally it would be very helpful to have input/output parameter clearly marked in the XML specification. I don't think this is done for Vulkan because structs are purely input or output.

**Comment by rpavlik** [comment]
Oh, interesting, I thought we only had purely-input or purely-output structs in public specs. It hadn't occurred to me that the struct-based two-call idiom in the visibility extension was one. (and I had somehow missed that MSFT had snuck in another two-call struct.)

The constness of the "next" parameter indicates whether something is used for output, I think - this is definitely something we have manually checked, not sure if it's in the tooling to check or not. (I don't see it offhand.)

so a few action items here:

- need some guidelines in the style guide for what to say about structs that are input/output.
- need a revision to at least the controller model extension to also say that.
- possibly something in the xml? You should be able to detect a two-call struct by name, though I think there may be an impending extension that has an in-out struct not like that (used as input in one place, output in another).  What's your use case for this data, and how does knowing something is in/out add utility above knowing it's at least output? (Also, will the incoming extension I mentioned where a struct is used in one place as a getter, and another place as a setter, mess you up?)

**Comment by expipiplus1** [comment]
>  What's your use case for this data, and how does knowing something is in/out add utility above knowing it's at least output?

My Haskell bindings do marshaling from Haskell to C for the user, so to the user they don't have to deal with the memory management themselves, knowing when to read and when to write with these allocations is quite important!

`Inout` or `Out` members of structs are a bit of a special case in my code currently, and I do treat them the same currently (I would like to change this in the long run though).

It's not the end of the world to fall back to user-managed memory for me though.

> Also, will the incoming extension I mentioned where a struct is used in one place as a getter, and another place as a setter, mess you up?

hahah, probably. In my Haskell bindings the definition of a struct varies depending on if the members are input or output. For this case I can probably fall back to having these members as non const pointers and having the user deal with marshaling things instead of the binding layer.

I can of course always special case these things, again, just effort :). 

I have some nice handling of two-call commands where both calls are made by my bindings, and a simple vector is returned. This is in principle possible for two-call structs, just engineering on my part.

My bindings are all machine generated, so the richer the information in the registry, the better.

**Comment by rpavlik** [comment]
Interesting. Some of the features sound a lot like OpenXR-Hpp (the C++ bindings - which have a similar two-call feature) as well as openxr-rs, rust bindings.

The implicit valid usage generator ("validitygenerator.py" iirc) knows basically how to distinguish input andoutput. I forgot about the returnedonly attribute. Basically folks tend to monkey with the XML until the generated spec text looks right and the API layers in the SDK generate and behave properly.

I do tend to agree that anything a computer might want to know or check should ideally be in the registry. I think interaction profile paths are one of the big remaining bits that are still in spec text only but I've got WIP for that.

If there's a way to augment the registry that you would suggest, perhaps an MR would be a good way to go - it could be just a partial one, just to pass around for concept review. Another bit to note is that our tooling is mostly shared with Vulkan and several other Khronos specs (and our XML is similarly related) so if this gets added here it may affect other APIs. And vice-versa: you may consider talking to/finding others who have bound other Khronos APIs to see what techniques they have used.

**Comment by rpavlik** [comment]
Closing this as it's generally in there though it could be documented better: A const next pointer means an input struct, like XrBaseInStructure, while a non-const next pointer means an output or input/output struct, like XrBaseOutStructure.
