### ISSUE TITLE
Registry XML contains unescaped '>' character

### ISSUE THREAD

**Issue by s-ol** [KhronosGroup/OpenXR-Docs#80]
Presumably this should have been escaped as `&gt;` like other such symbols in the same file.

https://github.com/KhronosGroup/OpenXR-Docs/blob/master/specification/registry/xr.xml#L124

I've also noticed that this XML contains an UTF-8 byte-order-mark, which the vulkan xml doesn't, though I'm not sure if this is expected to be consistent between these two or not.

**Comment by rpavlik** [comment]
I'm pretty sure the XML gets and loses a BOM every time I merge a merge request. I'm not sure which is better nor how to properly maintain the XML in such a way. Any thoughts?

**Comment by s-ol** [comment]
@rpavlik I only noticed because a simple parser I was using (copied from [Snektron/vulkan-zig](/Snektron/vulkan-zig)) broke because of it. Afaik the BOM is generally discouraged, especially with file formats that already have other ways to specify encoding. Since there already is the "encoding" parameter in the first line, the BOM is technically redundant. I think all parsers that understand the BOM will work without it, but that's not true the other way around.

It sounds like you or someone else that often works on this repo uses an editor that is configured to default to this encoding, even when the file is opened without it. I think most editors should have some settings for this.

**Comment by s-ol** [comment]
The unescaped `>` could also be detected by the xml-consistency script you mentioned in the other issue by the way.
