### ISSUE TITLE
Point of change for xrEnumerateBoundSourcesForAction is undefined

### ISSUE THREAD

**Issue by ZNixian** [KhronosGroup/OpenXR-Docs#82]
The docs don't specify when the results returned by `xrEnumerateBoundSourcesForAction` may change.

It makes sense that it can change when the actionsets passed to `xrSyncActions` change, but it's unclear whether it may change under other circumstances.

**Comment by rpavlik** [comment]
Fixed in 1.0.17. Thanks for your report!
