### ISSUE TITLE
Contradictory specified semantics for array getters

### ISSUE THREAD

**Issue by Ralith** [KhronosGroup/OpenXR-Docs#94]
[§2.11](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#buffer-size-parameters) says:
> Where the elementCapacityInput is non-zero but less than required, the function sets elementCountOutput to the required capacity, and must return XR_ERROR_SIZE_INSUFFICIENT. The data in elements is undefined.

The specification for `xrEnumerateInstanceExtensionProperties` says:
> propertyCountOutput is a pointer to the count of properties written, or a pointer to the required capacity in the case that propertyCapacityInput is 0.

Similar descriptions are given for `xrEnumerateApiLayerProperties`, `xrPathToString`, and presumably most other similar getters.

The latter text specifies that when `elementCapacityInput` is nonzero, the value pointed at by `elementCountOutput` becomes the number of elements written, which in the case of `XR_ERROR_SIZE_INSUFFICIENT` is undefined. The former text instead guarantees that the required capacity is written if `elementCapacityInput` is insufficient, regardless of whether `elementCapacityInput` is exactly zero or not.

Presuming the former text is the intended behavior, the descriptions for the count output parameters should be updated, perhaps by replacing "is 0" with "is insufficient."

**Comment by rpavlik** [comment]
I think the idea is that normal usage will be either

- pass sufficient capacity: get number of elements written, success.
- pass 0 as an explicit capacity query: get size required, success.

The excluded case in the per-function descriptions that you're highlighting is:

- pass != 0 but insufficient: get size required, error.

My impression is that the link in each of them to "more information" in the buffer size section should resolve this ambiguity, perhaps? I can see how this might be confusing to someone approaching this with a rust mindset :) Any hints on how to adjust the phrasing in such a way that doesn't distract from the intended two-step usage pattern above?

**Comment by Ralith** [comment]
> My impression is that the link in each of them to "more information" in the buffer size section should resolve this ambiguity, perhaps?

It's not just ambiguity, is the problem--the per-function text is specific that whenever capacity is nonzero, the output is the count written, not the capacity required, which directly contradicts the (more reasonable) text for the general case.

> I'd also be willing to take a s/CapacityInput is 0/CapacityInput is 0 or otherwise insufficient/ PR to the WG for review.

Your wording sounds reasonable to me; I appreciate the value of emphasizing the usefulness of passing 0, though the "Buffer Size Parameters" section does discuss this in detail regardless. Opened https://github.com/KhronosGroup/OpenXR-Docs/pull/104.

**Comment by s-ol** [comment]
@Ralith Can this be closed, seeing as #104 is merged?

**Comment by rpavlik** [comment]
I meant to close this, it's listed in that changelog too. Thanks for catching this.
